name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod init pinot-bot
        go mod tidy
        go get -v -t -d .

    - name: Build
      run: CGO_ENABLED=0 go build -v -tags netgo -ldflags "-extldflags '-static' -w" -o build/pinot-bot

    - name: Test
      run: go test -v .

#    - name: Publish
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: fx19880617/pinot-bot
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}